config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :assignments
    resources :classrooms
  end

  resources :assignments
  resources :classrooms
  
  get 'access/login' => 'access#login'
  get 'access/attempt_login' => 'access#attempt_login'
  post 'access/attempt_login' => 'access#attempt_login'
  get 'access/logout' => 'access#logout'

  root 'access#login'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :user
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :assignments
  belongs_to :classroom

  has_secure_password

  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def index
    @username = params[:username]
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      session[:first_name] = authorized_user.first_name
      session[:last_name] = authorized_user.last_name
      flash[:notice] = "You are now logged in as #{session[:first_name]} #{session[:last_name]}"
      redirect_to users_path
    else
      flash[:notice] = "Invalid username/password combination"
      redirect_to access_login_path
    end

  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "Logged out"
    redirect_to access_login_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def confirm_logged_in
    unless session[:user_id]
      redirect_to(:controller => 'access', :action => 'login')
      return false
    else
      return true
    end
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def user_admin
    redirect_to(access_login_path) unless current_user && current_user.admin == true
  end

  def correct_user
    @user = User.find(params[:id])
    unless user_admin
      redirect_to(access_login_path) unless @user == current_user
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  before_action :find_user

  def index
  #  @assignments = Assignment.all
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)

    if @assignment.save
      redirect_to assignment_path(@assignment)
    else
      render 'new'
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])

    if @assignment.update_attributes(assignment_params)
      redirect_to assignment_path(@assignment)
    else
      render 'edit'
    end
  end

  def delete
    @assignment = Assignment.find(params[:id])
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_path
  end

  private

  def assignment_params
    params.require(:assignment).permit(:title, :content, :user_id, :classroom_id)
  end

  def find_user
    if params[:user_id]
      @assignments = Assignment.where(user_id: params[:user_id])
    else
      @assignments = Assignment.all
    end
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController


  def index
    @classrooms = Classroom.all
  end

  def show
    @classroom = Classroom.find(params[:id])
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      redirect_to classroom_path(@classroom)
    else
      render 'new'
    end
  end

  def edit
    @classroom = Classroom.find(params[:id])
  end

  def update
    @classroom = Classroom.find(params[:id])

    if @classroom.update_attributes(classroom_params)
      redirect_to classroom_path(@classroom)
    else
      render 'edit'
    end
  end

  def delete
    @classroom = Classroom.find(params[:id])
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy
    redirect_to classrooms_path
  end

  private

  def classroom_params
    params.require(:classroom).permit(:title, :teacher)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_classroom
  
  def index
  #  @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :admin, :classroom_id)
  end

  def find_classroom
    if params[:user_id]
      @users = User.where(classroom_id: params[:classroom_id])
    else
      @users = User.all
    end
  end

end

app/helpers/access_helper.rb
module AccessHelper
  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def user_admin?
    current_user.admin == true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
    <table>
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>

      <tr>
        <th>&nbsp;</th>
        <td><%= submit_tag("Log In", class: 'btn btn-inverse') %></td>
      </tr>
    </table>
    <hr>
  <% end %>
</div>

app/views/application/_navigation.html.erb
<nav>
  <li><%= link_to 'Users', users_path %></li>
  <% if logged_in? %>
    <li><%= link_to 'Assignments', user_assignments_path(current_user) %></li>
    <li><%= link_to 'Classes', user_classrooms_path(current_user) %></li>

  <% end %>
</nav>

app/views/assignments/_assignment.html.erb
<h2><%= assignment.title %></h2><br>
<p>
  <%= assignment.content %>
</p><br>

app/views/assignments/_form.html.erb
<table class="table-condensed">
  <tr>
    <th><%= f.label(:title) %></th>
    <td><%= f.text_field(:title) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:content) %></th>
    <td><%= f.text_area(:content) %></td><br>
  </tr>
  
</table>

app/views/assignments/edit.html.erb
<%= form_for @assignment do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update Assignment", class: 'btn btn-inverse') %>
<% end %>

app/views/assignments/index.html.erb
<% @assignments.each do |assignment| %>
<%= link_to assignment.title, assignment_path(assignment) %><br>
<% end %>

app/views/assignments/new.html.erb
<h2>New Assignment</h2>
<%= form_for @assignment do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create Assignment', class: 'btn btn-inverse') %>
<% end %>

app/views/assignments/show.html.erb
<%= render partial: 'assignment', locals: { assignment: @assignment } %>

app/views/classrooms/_classroom.html.erb
<h2><%= classroom.title %></h2>
<p>
  <% classroom.users.each do |user| %>
  <%= user.name %>
  <% end %>
</p>

app/views/classrooms/_form.html.erb
<table class="table-condensed">
  <tr>
    <th><%= f.label(:title) %></th>
    <td><%= f.text_field(:title) %></td><br>
  </tr>

</table>

app/views/classrooms/edit.html.erb
<%= form_for @classroom do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update Classroom", class: 'btn btn-inverse') %>
<% end %>

app/views/classrooms/index.html.erb
<% @classrooms.each do |classroom| %>
<%= link_to classroom.title, classroom_path(classroom) %><br>
<% end %>

app/views/classrooms/new.html.erb
<h2>New Classroom</h2>
<%= form_for @classroom do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create Classroom', class: 'btn btn-inverse') %>
<% end %>

app/views/classrooms/show.html.erb
<%= render partial: 'classroom', locals: { classroom: @classroom } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'application/navigation' %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<table class="table-condensed">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td><br>
  </tr>
  <tr>
      <th><%= f.label(:username) %></th>
      <td><%= f.text_field(:username) %></td><br>
  </tr>
  <tr>
      <th><%= f.label(:password) %></th>
      <td><%= f.password_field(:password) %></td>
  </tr>
  <tr>
    <th><%= f.label(:confirm) %></th>
    <td><%= f.password_field(:password_confirmation) %></td>
  </tr>
</table>

app/views/users/_user.html.erb
<h2><%= user.name %></h2>
<table>
  <% user.assignments.each do |assignment| %>
    <tr>
      <th>
        <%= link_to assignment.title, assignment_path(assignment) %>
      </th>

    </tr>
    <% end %>
</table>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update User", class: 'btn btn-inverse') %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= link_to user.name, user_path(user) %><br>
<% end %>

app/views/users/new.html.erb
<h2>New User</h2>
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create User', class: 'btn btn-inverse') %>
<% end %>

app/views/users/show.html.erb
<%= render partial: 'user', locals: { user: @user } %>